[purrcrypt]
source = "cmd"
cmd = """
  bash -lc '
    tmp=$(mktemp -d)
    git clone --quiet --bare https://github.com/vxfemboy/purrcrypt.git "$tmp"

    # Get hash of last commit that touched package-relevant files (including merges)
    last_commit=$(git --git-dir="$tmp" log -1 --first-parent --format="%H" -- Cargo.toml Cargo.lock src/ LICENSE purrcrypt-demo.gif)

    if [ -n "$last_commit" ]; then
      count=$(git --git-dir="$tmp" rev-list --count "$last_commit")
      short=$(git --git-dir="$tmp" rev-parse --short=7 "$last_commit")
      printf "r%s.%s\n" "$count" "$short"
    fi

    rm -rf "$tmp"
  '
"""
