[archivemount-ng]
source = "cmd"
cmd = '''
git ls-remote --tags https://git.sr.ht/~nabijaczleweli/archivemount-ng \
  | awk -F/ '/refs\/tags\/[0-9]+[a-z]?$/ {print $3}' \
  | sort -V \
  | tail -n1
'''
